FROM continuumio/miniconda3:latest
MAINTAINER Leighton Pritchard <leighton.pritchard@hutton.ac.uk>

RUN apt-get update

RUN conda install jupyter -y

RUN conda config --add channels conda-forge
RUN conda config --add channels r
RUN conda config --add channels bioconda

RUN conda install -c bioconda blast biopython bioservices
RUN conda install seaborn

RUN useradd -ms /bin/bash ibioic
USER ibioic
WORKDIR /home/ibioic

RUN git clone https://github.com/widdowquinn/2018-03-06-ibioic.git /home/ibioic/2018-03-06-ibioic

CMD jupyter notebook --ip="*" --allow-root --notebook-dir=/home/ibioic/2018-03-06-ibioic --port=8888 --no-browser

#ENTRYPOINT ["/bin/bash"]