---
title: "Course Schedule<br />6-7/3/2018"
output: 
  revealjs::revealjs_presentation:
    theme: white
    center: true
    highlight: pygments
    transition: fade
    css: reveal.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Installation instructions

* <https://2018-03-06-ibioic.readthedocs.io/en/latest/installation_attendees.html>
* <http://bit.ly/2I416Gg>

## Schedule: Day 1

**Morning, 0930-1230**

* Welcome and introduction (Leighton, Sue, Peter)
* Introduction to Linux, Jupyter and Python (Peter)
* Introduction to sequence data and bioinformatics (Peter)

**Afternoon, 1330-1700**

* Mining bioinformatics databases (Leighton)

## Schedule: Day 2

**Morning, 0930-1230**

* Reproducible research (Leighton)
* Worked example (Peter, Leighton, Sue)

**Afternoon, 1330-1700**

* Structural bioinformatics (Sue)
* Conclusion and wrap-up (Leighton, Peter, Sue)

# Goals

## Course goals

Provide an introduction to

* basic computing skills in bioinformatics
* common bioinformatics tools
* automation and reproducible research
* best proactices in scientific computing

## Best practices in scientific computing

* Write reproducible analyses for people, not computers.
* Let the computer do the work.
* Use a version control system.
* Don't repeat yourself (or others).
* Plan for mistakes.
* Collaborate.

(abridged from [Wilson *et al.* (2014)](http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1001745))